### ISSUE TITLE
Installer wizard discards sphinx conf, new conf blank

### ISSUE THREAD

**Issue by whodafly** [bauerjj/SphinxSearchPlugin#23]
I'm trying to set up Sphinx search for my Vanilla forums. Right now I'm setting up a test instance of everything, and I've got Vanilla and MariaDB running in Docker containers. I have a Sphinx container too, but I want to set up the configuration as part of creating the Docker image.

I used the Installation Wizard, and I pasted my sphinx.conf file in there and pressed Save and Continue, and both the old and new conf are empty, except for "Paste Your Text Here" in both. I don't see any errors in the UI.

I've checked my config file, and it doesn't have the conf, although it does seem to be writeable as I can modify the settings of other Vanilla plugins without a problem (and enable the Sphinx Search plugin too).

Any ideas?

I tried finding the config in your repository, but I'm not a PHP developer, so I can't seem to figure out where it is, or what it should be.

**Comment by bauerjj** [comment]
Hi,

What version of vanilla are you using? I haven't used vanilla in a few years. The config file is local to your vanilla forums install. It contains settings such as db username and password. Can you check to see if it contains any mention of sphinxsearch in there? There should be multiple entries of variables and such. 

If you want, can you `print_r $ReWritedContent` just after here? https://github.com/bauerjj/SphinxSearchPlugin/blob/master/class.sphinxsearchinstall.php#L104

This should contain your new config. If not, then we can place a few more print statements to see where the plugin is failing.

**Comment by whodafly** [comment]
I'm running Vanilla 2.3.1.

I managed to find the sphinx.conf.tpl file in the repository, and figured out what variables should be replaced, so now I'm just trying to get searchd to run (it's failing currently, but I'm not sure why, probably a configuration issue).

(By the way, I just noticed on your profile that you're from AZ, same here :-) )

**Comment by bauerjj** [comment]
yes, I was just going to suggest that you could also manually fill in the variables by looking at your original sphinx.conf and your db credentials. Are you trying to get `searchd` running on your host? Is it a shared system or is it a local setup? Sphinx is generally pretty good at spitting out verbose errors if there is a problem with the configuration. You will also need to set some variables to be `TRUE` inside of your vanilla configuration file under the `sphinxsearch` array so that the plugin knows that it can run. The wizard would usually set these to be true, but by circumventing this you will need to manually set these. 

yep, Tempe, AZ

**Comment by whodafly** [comment]
I've used Sphinx before (although it was a few years ago), so I'm fairly familiar with it. I'm using it in a Docker container that I've made on my VPS. I'll figure out what searchd's problem is :-) I was basically just looking for the sources and indexes I needed for the plugin.

I ran the wizard up to the point of the updated config. I'll check the Vanilla config file for additional settings.

Ah, I'm in Tuscon.

**Comment by bauerjj** [comment]
ok, lets us know how it works out

**Comment by whodafly** [comment]
Right, so I had a couple of syntax errors (I'm a bit OCD, so I reformatted the SQL queries and forgot a couple of \'s), but there are some other options in the template config that are no longer valid in Sphinx (I'm running 2.2.11):

```
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'ondisk_dict' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'port' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'max_matches' was permanently removed from Sphinx configuration. Refer to documentation for details.
ERROR: unknown key name 'compat_sphinxql_magics' in /etc/sphinx/sphinx.conf
```

Once I removed those, searchd was happy.

**Comment by bauerjj** [comment]
Hm, OK. Did you run the indexer too? Now go to your website and see if the new search is working.

**Comment by whodafly** [comment]
Yep, indexer also working fine. Need to fix the Vanilla config and then I should be able to test.

**Comment by bauerjj** [comment]
I just looked at the code again and I think that as long as the plugin is enabled, the new search should be using sphinx.

**Comment by whodafly** [comment]
Yes it is. There are a few other issues now, but I have Sphinx up and running, and Vanilla is using the Sphinx Search plugin for searching.

**Comment by bauerjj** [comment]
cool - be sure to also checkout this plugin for some syntax help while searching: https://open.vanillaforums.com/addon/sphinxsearchsyntaxdropdown-plugin

**Comment by whodafly** [comment]
OK, last issue I had was a problem with the stats table. There's a "keywords_full" column which apparently is not being used, but is set to NOT NULL, and has a default value of NULL. This causes an exception to be thrown when searching. I initially just altered the column in the database, and then I disabled the stats in the search settings.

Once I had done this, the Sphinx search worked beautifully. **So much better** than the fulltext search in MariaDB.

**Comment by bauerjj** [comment]
hm, alright. I wonder why that throws an exception inside the PHP code. I'll have to revamp the plugin for the newer versions of vanilla. I'm glad that they didn't change the database structure. I'm glad that you got it sorted!

**Comment by whodafly** [comment]
The exception is thrown because the SQL statement doesn't include the keywords_full column when inserting a row into the table, so MariaDB returns an error message when trying to save the search statistics, and then Vanilla's DB layer converts that into an exception (from what I can see -- again, I'm not familiar with Vanilla's internals nor with PHP).

**Comment by bauerjj** [comment]
Ah OK. Makes sense. Now I'm wondering why this error hasn't come up before when it was initially released. I'll have to dig deeper.
