### ISSUE TITLE
Unable enable plugin Vanilla 2.5 with PHP 7.1

### ISSUE THREAD

**Issue by gamunu** [bauerjj/SphinxSearchPlugin#24]
Cannot declare class Widgets, because the name is already in use in plugins/SphinxSearch/widgets/class.widgets.php on line 3

https://github.com/bauerjj/SphinxSearchPlugin/blob/e741c2ce37616f1e823d5420a0ce9550b6d6d4a4/class.sphinxsearch.plugin.php#L105

https://github.com/bauerjj/SphinxSearchPlugin/blob/e741c2ce37616f1e823d5420a0ce9550b6d6d4a4/class.sphinxsearch.plugin.php#L116

https://github.com/bauerjj/SphinxSearchPlugin/blob/e741c2ce37616f1e823d5420a0ce9550b6d6d4a4/class.sphinxsearch.plugin.php#L127

**Comment by eythian** [comment]
Adding my +1 too, this is happening to me in Vanilla 2.5.1 w/ PHP 7.0.27

**Comment by bauerjj** [comment]
@yhdleung can you fork and then put in those edits and issue a pull request? I'm going to test this plugin with the latest.

**Comment by yhdleung** [comment]
@bauerjj  yes, created the pull request #27 .
